name: build and test
on: [push, pull_request]
jobs:
  build:
    name: Build
    steps:
      - name: checkout master
        uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: BSuild
        run: go build -v
      - name: test
        run: go test -v

  test:
    name: Test
    steps:
      - name: checkout master
        uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: test
        run: go test -v