name: build and test
on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master
jobs:
  build-test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Build
        run: go build -v
      - name: test
        run: go test -v